# supabase/config.toml

project_id = "jzjwaadxzaqvsjcnqabj"

[functions.generate-posters]
  verify_jwt = true 

[functions.create-checkout-session]
  verify_jwt = true

[functions.stripe-webhook]
  verify_jwt = false

