// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzjwaadxzaqvsjcnqabj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6andhYWR4emFxdnNqY25xYWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTc3MjAsImV4cCI6MjA2MzczMzcyMH0.QDYgwmuFrKMqK6U8YQmJLo_2oow2iL1Lhx37XRRD4UU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);